name: Golang with cache

inputs:
  version:
    description: Golang version.
  version-file:
    description: Golang version from go.mod. Used in place of `version`.
  cache-key-suffix:
    description: Optional cache key suffix.
    default:

runs:
  using: composite
  steps:
    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.version }}
        go-version-file: ${{ inputs.version-file }}
    - name: Determine cache paths
      id: golang-path
      run: |
        echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
        echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
      shell: bash
    - name: Setup Golang cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.golang-path.outputs.build }}
          ${{ steps.golang-path.outputs.module }}
        key: ${{ runner.os }}-golang${{ inputs.cache-key-suffix }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang${{ inputs.cache-key-suffix }}-
