name: Golang with cache

inputs:
  version:
    description: Golang version.
    default:
  version-file:
    description: Golang version from go.mod. Used in place of `version`.
    default:
  cache-key-suffix:
    description: Optional cache key suffix.
    default:

runs:
  using: composite
  steps:
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version: ${{ inputs.version }}
        go-version-file: ${{ inputs.version-file }}
    - name: Determine cache paths/cache key
      id: vars
      run: |
        echo "path-build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
        echo "path-module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"

        cacheKeyRoot="golang-${{ runner.os }}${{ inputs.cache-key-suffix && format('-{0}',inputs.cache-key-suffix) }}-"
        echo "cache-key-restore=$cacheKeyRoot" >>"$GITHUB_OUTPUT"
        echo "cache-key=${cacheKeyRoot}${{ hashFiles('**/go.sum') }}" >>"$GITHUB_OUTPUT"
      shell: bash
    - name: Setup Golang cache
      uses: actions/cache@v3
      with:
        key: ${{ steps.vars.outputs.cache-key }}
        path: |
          ${{ steps.vars.outputs.path-build }}
          ${{ steps.vars.outputs.path-module }}
        restore-keys: |
          ${{ steps.vars.outputs.cache-key-restore }}
